Repository WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team1, pull requests merged in 2022-11, with the labels that each got.

#5 One product
  frontend/.eslintrc.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/next.png
  frontend/src/assets/previous.png
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#6 Basket
  frontend/src/App.css
  frontend/src/Basket.css
  frontend/src/components/Basketcard.jsx
  frontend/src/pages/Basket.jsx
Labels: Change requested

#7 All products
  .vscode/settings.json
  frontend/index.html
  frontend/src/App.jsx
  frontend/src/PokemonList.css
  frontend/src/components/PokemonCard.jsx
  frontend/src/components/PokemonList.jsx
  frontend/src/pages/AllProducts.jsx
  frontend/src/services/pokemons.js
Labels: Review Done

#8 Header
  frontend/src/App.jsx
  frontend/src/assets/Burger.png
  frontend/src/assets/logo.png
  frontend/src/assets/panier.png
  frontend/src/components/Header.css
  frontend/src/components/Header.jsx
  frontend/src/components/Navbar/NavbarWindow.jsx
Labels: Review Done, Reviewer One OK

#9 Home
  frontend/src/Home.css
  frontend/src/pages/Home.jsx
Labels: Review Done, Reviewer One OK

#13 add one product on systeme on nav
  frontend/src/App.jsx
Labels: Review Done, Reviewer One OK

#14 hotfix App.jsx
  frontend/src/App.jsx
Labels: Review Done, Reviewer One OK

#12 Home
  frontend/src/Home.css
  frontend/src/pages/Home.jsx
Labels: Review Done, Reviewer One OK

#19 Table
  backend/database.sql
Labels: Review Done

#16 All products part2
  frontend/src/App.jsx
  frontend/src/assets/search.svg
  frontend/src/components/Header.css
  frontend/src/components/Header.jsx
  frontend/src/components/PokemonList.jsx
  frontend/src/components/Search.jsx
  frontend/src/pages/AllProducts.jsx
Labels: Review Done, Reviewer One OK

#15 refactoring oneProduct.jsx
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Avis.jsx
  frontend/src/components/PokemonStat.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Review Done

#21 update branche footer pour pr
  frontend/src/App.jsx
  frontend/src/assets/facebook.png
  frontend/src/assets/insta.png
  frontend/src/assets/twitter.png
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
Labels: Review Done, Reviewer One OK

#24 Form modifications
  frontend/src/components/Form.jsx
Labels: Review Done, Reviewer One OK

#25 hotfix footer, basketcard
  frontend/src/components/Basketcard.jsx
  frontend/src/components/Footer.jsx
  frontend/src/pages/Basket.jsx
Labels: Reviewer One OK

#26 Caroussel
  frontend/index.html
  frontend/src/Home.css
  frontend/src/assets/Hard_choose_home.png
  frontend/src/pages/Home.jsx
Labels: Review Done

#28 setting emailjs service
  frontend/.env.sample
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Form.jsx
Labels: Review Done

#29 form hotfix
  frontend/src/components/Form.jsx
Labels: Reviewer One OK

#30 fix basket non terminer
  frontend/src/pages/Basket.jsx
Labels: Review Done, Reviewer One OK

#31 Router front
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Form.jsx
  frontend/src/components/Header.css
  frontend/src/components/Navbar/NavbarWindow.jsx
  frontend/src/components/PokemonCard.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Review Done, Reviewer One OK

#32 Hotfix css
  frontend/src/PokemonList.css
  frontend/src/components/Header.css
  frontend/src/components/Header.jsx
  frontend/src/components/Navbar/NavbarWindow.jsx
  frontend/src/components/PokemonList.jsx
  frontend/src/components/Search.jsx
Labels: Review Done, Reviewer One OK

#33 add crete state form panier and implement add and delete
  frontend/src/App.jsx
  frontend/src/Basket.css
  frontend/src/components/Basketcard.jsx
  frontend/src/pages/Basket.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Review Done, Reviewer One OK

#35 redesign footer
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
Labels: Review Done, Reviewer One OK

#37 contact title fix
  frontend/src/App.css
  frontend/src/components/Form.jsx
Labels: Reviewer One OK

#38 ajout de la police + couleur footer
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
Labels: Review Done, Reviewer One OK

#36 Pokemon delete basket
  frontend/src/App.jsx
  frontend/src/components/Basketcard.jsx
  frontend/src/pages/Basket.jsx
Labels: Change requested, Review Done, Reviewer One OK

#41 Maj data
  backend/src/data/pokemons.js
Labels: Reviewer One OK

#45 One product fixes
  frontend/src/App.css
  frontend/src/components/Form.jsx
Labels: Review Done, Reviewer One OK

#42 Hotfix header part2
  frontend/src/components/Header.jsx
Labels: Review Done, Reviewer One OK

#44 Hotfix footer
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
Labels: Change requested, Review Done

#46 setting alert when submitting form with toastify
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Form.jsx
Labels: Conflict detected

#49 Ajout métas titre et description et favicon
  frontend/index.html
  frontend/src/assets/favicon.svg
  frontend/src/pages/AllProducts.jsx
  frontend/src/pages/Basket.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/OneProduct.jsx
  frontend/src/services/seo.js
Labels: Review Done

#50 Refactorisation du Search
  frontend/src/components/Search.jsx
Labels: Review Done

#51 Quantity fonctionnel
  frontend/src/App.jsx
  frontend/src/Basket.css
  frontend/src/components/Basketcard.jsx
  frontend/src/pages/Basket.jsx
Labels: Review Done, Reviewer One OK

#52 Router
  backend/src/db.js
  backend/src/router.js
  frontend/src/components/PokemonCard.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/OneProduct.jsx
Labels: Review Done, Reviewer One OK

#53 les boutons des news fonctionnent
  backend/src/router.js
  frontend/src/pages/Home.jsx
Labels: Review Done, Reviewer One OK

#54 les boutons du carousel fonctionnent
  frontend/src/pages/Home.jsx
Labels: Review Done, Reviewer One OK

#55 Summer order dynamique
  frontend/src/App.jsx
  frontend/src/components/Basketcard.jsx
  frontend/src/pages/Basket.jsx
Labels: Reviewer One OK

#57 add card ajoute quantité et non plus un nouveau produit
  frontend/src/App.jsx
Labels: Reviewer One OK

#56 Mise en place du filtre par type + Hotfix
  frontend/src/PokemonList.css
  frontend/src/components/PokemonList.jsx
  frontend/src/pages/Home.jsx
Labels: Reviewer One OK

#58 HotFixLink
  frontend/src/components/Footer.jsx
  frontend/src/pages/Home.jsx
Labels: Review Done, Reviewer One OK

#61 news buttons fix
  frontend/src/pages/Home.jsx
Labels: Review Done, Reviewer One OK

#62 carousel buttons size fix
  frontend/src/pages/Home.jsx
Labels: Review Done, Reviewer One OK

#63 HotfixFilter
  frontend/src/components/PokemonList.jsx
Labels: Reviewer One OK

#65 Fix taille texte panier vide, création fonction pour vider panier a l…
  frontend/src/App.jsx
  frontend/src/pages/Basket.jsx
Labels: Review Done, Reviewer One OK
